/*ESTRUTURA DE  REPETIÇÃO ANINHADA
if(CONDIÇÃO 1){

    INSTRUÇÕES CASO CONDIÇÃO 1 RETORNE VERDADEIRO
}

else if(condição 2){

     INSTRUÇÕES CASO CONDIÇÃO 2 RETORNE VERDADEIRO
}

else if(condição 3){

     INSTRUÇÕES CASO CONDIÇÃO 3 RETORNE VERDADEIRO
}

else{

    INSTRUÇÕES CASO CONDIÇÕES ANTERIORES RETORNE FALSO
}
*/