/*           ESTRUTURA DE CONTROLE DE REPETIÇÃO

=> EXISTEM TRÊS ESTRUTURA DE REPETIÇÃO:ENQUANTO;REPITA; PARAR

=> EM MUITOS CASOS É NECESSÁRIO REPETIR UM TRECHO DE UM PROGRAMA DIVERSAS VEZES. NESSE CASO
PODEMOS USAR UM "LOOP" QUE EFETUE ESSA REPETIÇÃO DE CÓDIGO QUANTAS VEZES FOREM NECESSÁRIAS.

=> OS LOOPS SÃO CHAMADOS TAMBÉM DE LAÇO DE REPETIÇÃO.

=> ESSA ESTRUTURA REALIZA UM TESTE LÓGICO NO INICIO DO LOOP, E CADA VEZ QUE O TESTE RETORNA O VALOR
VERDADEIRO, OS COMANDOS ASSOCIADOS AO LAÇO SÃO EXECUTADOS.

=> QUANDO O TESTE RETORNAR FALSO, O LAÇO É ENCERRADO E O PROCESSAMENTO VOLTA PARA O FLUXO PRINCIPAL DO
PROGRAMA.

=> REPETIÇÃO COM TESTE LÓGICO NO INICIO
=> WHILE = ENQUANTO

                SINTAXE DE WHILE

while(condição){

    instrução executadas enquanto condição verdadeira
}

=> MUDANDO O FLUXO DE UM LAÇO:

comando continue => toda vez que encontrar um continue vai igonorar o intrução e voltar pra o começo do laço

=>INTERRONPER O FLUXO:

comando Break => interronpe o laço






*/

